# See https://pre-commit.com/ for usage and config
repos:
 - repo: https://github.com/pycqa/isort
   rev: 5.12.0
   hooks:
    - id: isort
      name: isort (python)
      stages: [ commit ]
      language: system
      types: [ python ]
 - repo: https://github.com/psf/black
   rev: 23.3.0
   hooks:
    - id: black
      name: black
      stages: [ commit ]
      types: [ python ]
# - repo: https://github.com/pycqa/flake8
#   rev: '6.0.0'  # pick a git hash / tag to point to
#   hooks:
#    - id: flake8
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: 'v1.4.1'  # Use the sha / tag you want to point at
#   hooks:
#    - id: mypy
#      pass_filenames: false
#      language: system
#      args: [
#       '--package',
#       'stitcher.operation_executor'
#      ]
# - repo: local
#   hooks:
#    - id: pytest
#      name: pytest
#      stages: [ commit ]
#      language: system
#      entry: pytest test
#      types: [ python ]
#      pass_filenames: false
#    - id: pytest-cov
#      name: pytest
#      stages: [ push ]
#      language: system
#      entry: pytest --cov --cov-fail-under=100 test
#      types: [ python ]
#      pass_filenames: false
